Feature/zaken list sort einddatum rebase
open-zaak/open-zaak pull request #1068
Opened 2021-11-23 08:30 UTC by stevenbal

Fixes #

**Changes**

[Describe the changes here]

2021-11-23 08:57 UTC, stevenbal commented
replacement for https://github.com/open-zaak/open-zaak/pull/1045

2023-06-22 12:21 UTC, annashamray requested changes
Could you please rebase on `main` one more time? Just to make sure that the CI will pass

2023-06-22 12:21 UTC, annashamray commented on src/openzaak/components/zaken/api/filters.py
> +            mark_oas_difference("Het veld waarop de resultaten geordend worden.")
I think it's not a deviation from OAS anymore, so this mark can be removed

2023-08-22 14:56 UTC, annashamray commented
replace with new PR #1445

2023-08-22 14:56 UTC, closed without merging