Change product steering team to core group
open-zaak/open-zaak pull request #1096
Opened 2022-02-03 13:28 UTC by Ainali

Changed product steering team to core group, and removed specifics about their process.

Fixes #781

2022-02-03 13:29 UTC, ericherman requested changes

2022-02-03 13:29 UTC, ericherman commented on CONTRIBUTING.md
> +* support the technical steering teams
singular vs plural

2022-02-03 20:58 UTC, joeribekker approved these changes

2022-02-07 08:43 UTC, ericherman approved these changes

2022-02-08 08:34 UTC, Ainali commented
Thanks for the reviews. Can you merge it @joeribekker? (I don't have the rights to do it)

2022-02-09 11:03 UTC, merged