:hammer: [#1215] Add script to dump config from database
open-zaak/open-zaak pull request #1216
Opened 2022-07-15 10:32 UTC by stevenbal

Requires https://github.com/maykinmedia/zgw-consumers/pull/44 to be merged and zgw_consumers version to be bumped

Fixes #1215

**Changes**

* Add script to dump config from database

2022-07-15 17:56 UTC, sergei-maertens requested changes
I think we're missing:

* `vng_api_common.JWTSecret`
* `autorisaties.Applicatie` & related permissions (so that other services can connect to Open Zaak)
* `notifications.NotificatiesConfig` & webhook subscriber information (latter should be empty though?)

2022-07-18 12:20 UTC, stevenbal commented on bin/dump_configuration.sh
> +                zgw_consumers.Certificate \
Would dumping the files to a .zip archive work? https://github.com/maykinmedia/zgw-consumers/pull/44

2022-07-18 15:53 UTC, sergei-maertens commented on bin/dump_configuration.sh
> +                zgw_consumers.Certificate \
yeah, should be fine - as long as the files can be matched & imported again (relatively) easily

2022-07-22 15:48 UTC, sergei-maertens commented
zgw-consumers 0.19.0 was published today!

2022-07-25 08:51 UTC, sergei-maertens requested changes
Can you make the script a bit more in line with the version in Open Forms: https://github.com/open-formulieren/open-forms/blob/master/bin/dump_configuration.sh

* Creating a temporary directory to dump to
* Support `TMPDIR` environment variable

-> this makes it so we can mount a volume and don't need to write to the container file system, which is usually advised against.

* Include comments in the script on how to use it, and ensure the certificate files are dumped as well.

2022-07-25 13:35 UTC, sergei-maertens approved these changes

2022-07-25 13:35 UTC, merged