:bookmark: release Open Zaak 1.9.0
open-zaak/open-zaak pull request #1409
Opened 2023-07-17 13:13 UTC by annashamray

Fixes #1408

2023-07-18 13:00 UTC, joeribekker requested changes

2023-07-18 13:24 UTC, annashamray commented on CHANGELOG.rst
> +* [#1310] add support for Elastic APM
Done

2023-07-20 09:09 UTC, annashamray commented on CHANGELOG.rst
> +* [#1344] add management command to generate large amount of data for performance test
comment to myself - add info about InformatieObjecten performance

2023-07-20 13:46 UTC, annashamray commented on CHANGELOG.rst
> +* [#1344] add management command to generate large amount of data for performance test
@joeribekker I added more details about optimization changes

2023-07-21 08:07 UTC, merged