:bug:[#1474] fix exception thrown with bad catalogus ID
open-zaak/open-zaak pull request #1523
Opened 2023-12-05 11:02 UTC by Coperh

Fixes #1474

**Changes**
Catch related object does not exist exception

2023-12-05 11:05 UTC, Coperh commented on src/openzaak/components/catalogi/admin/forms.py
> +            msg = _("Catalogus provided does not exist")
What should this error be? What is the translation?

2023-12-05 16:06 UTC, annashamray requested changes

2023-12-06 15:10 UTC, annashamray commented
@Coperh Could you please either resolve conversations or answer my comments, so I would know which comments are addressed?

2023-12-06 15:34 UTC, Coperh commented on src/openzaak/components/catalogi/models/mixins.py
> +            raise ValidationError(_("Catalogus provided does not exist"))
Suggestion implemented. 
Also removed Validation error.

2023-12-06 15:35 UTC, Coperh commented on src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py
> +        form["catalogus"] = 16
Empty case is added.

2023-12-06 16:00 UTC, Coperh commented
@annashamray yep, sorry.

That is done now.

2023-12-07 15:01 UTC, annashamray approved these changes

2023-12-11 09:08 UTC, merged