:sparkles: [#1637] added 2fa
open-zaak/open-zaak pull request #1644
Opened 2024-05-03 09:24 UTC by bart-maykin

Fixes [#1637](https://github.com/open-zaak/open-zaak/issues/1637)

Added 2fa

2024-05-07 14:46 UTC, stevenbal commented on src/openzaak/templates/maykin_2fa/base.html
> +{% endblock %}
Same comment as for ON, this file can be removed

2024-05-07 14:46 UTC, stevenbal commented on src/openzaak/templates/maykin_2fa/login.html
> +{% endblock %}
Same comment as for ON, this block can be removed
```suggestion
```

2024-05-30 09:26 UTC, stevenbal commented on src/openzaak/templates/maykin_2fa/base.html
> +{% endblock %}
Sorry, I was wrong about removing the `base.html` file, it turns out Open Zaak does use this `footer` block https://github.com/open-zaak/open-zaak/blob/e701f8155735949033fc53f0c78ac4ce9fcc97ca/src/openzaak/templates/admin/base_site.html#L43 (while Open Notificaties does not). Could you re-add it here?

2024-05-30 09:29 UTC, stevenbal requested changes
Just the last comment to re-add `base.html`, then I'll approve

2024-06-04 11:28 UTC, stevenbal approved these changes

2024-06-04 12:53 UTC, merged

2024-06-14 12:25 UTC, annashamray commented
What about backward compatibility? Now we will force all our clients to set up 2fa for the admin without any notice. 
@bart-maykin please make it possible to disable it for now. 
We will announce this feature but not make it required this time