[#1812] Auto fill in zaak.startdatum_bewaartermijn
open-zaak/open-zaak pull request #1813
Opened 2024-11-18 14:05 UTC by alextreme

Fixes #1812

2025-02-11 11:56 UTC, stevenbal requested changes
@annashamray could you address the missing coverage for `brondatum.py`?

2025-02-11 11:56 UTC, stevenbal commented on src/openzaak/components/zaken/brondatum.py
> +            self.zaak.einddatum = orig_value
I haven't looked into this, but would it take a lot of effort to refactor this to remove this zaak.einddatum mutation?

2025-02-20 09:09 UTC, annashamray commented
@stevenbal  I've improved patch codecov, but general codecov still doesn't like it. 
Could we just merge it?

2025-02-20 10:46 UTC, stevenbal approved these changes

2025-02-20 11:22 UTC, merged