Feature/monitoring hide sensitive data
open-zaak/open-zaak pull request #697
Opened 2020-08-24 10:57 UTC by stevenbal

Fixes #696 

**Changes**

* Switched from raven to sentry_sdk
* Added `before_send` function to `sentry_sdk.init` that filters out sensitive data from the events

2020-08-25 16:12 UTC, joeribekker requested changes

2020-08-25 16:12 UTC, joeribekker commented on requirements/base.in
>  raven  # error monitoring sentry
Raven can be out then?

2020-08-25 16:12 UTC, joeribekker commented on src/openzaak/utils/monitoring.py
> +    return event
Looks good but is it possible to test this? With a unit test?

2020-08-25 16:12 UTC, joeribekker commented on src/openzaak/conf/includes/base.py
> +        "release": os.getenv("RELEASE", "RELEASE not set"),
The RELEASE variable is already initialized. Why grab it from the env again and miss out on the GIT_SHA alternative?

```suggestion
        "release": RELEASE or "RELEASE not set",
```

2020-08-27 11:00 UTC, sergei-maertens requested changes

2020-08-28 15:32 UTC, joeribekker approved these changes

2020-08-28 15:33 UTC, merged