Fixes 584 download non existing EIO causes 500 error
open-zaak/open-zaak pull request #728
Opened 2020-10-01 08:58 UTC by SilviaAmAm

Fixes #584 

**Changes**
Added a check for when strings are passed to the `BinaryFileRenderer`

In the case where there is an error response and the renderer is `BinaryFileRenderer`, the response content is a string rather than binary data. If a renderer returns a string, the `Response` class attempts to encode it using the specified charset. 
In the `BinaryFileRenderer` the charset is set to `None`, so this caused an error.
Now, inside `BinaryFileRenderer` there is a check for string responses, which are then encoded to UTF-8.

2020-10-02 14:36 UTC, stevenbal approved these changes

2020-10-09 15:25 UTC, sergei-maertens requested changes
Can you also rebase on master and resolve the merge conflict please?

2020-10-09 15:25 UTC, sergei-maertens commented on src/openzaak/components/documenten/api/renderers.py
> +import six
no reason to use `six`, Python 2 is dead an burried

2020-10-09 15:25 UTC, sergei-maertens commented on src/openzaak/components/documenten/api/renderers.py
> +        if isinstance(data, six.text_type):
```suggestion
        if isinstance(data, str):
```

2020-10-16 09:46 UTC, sergei-maertens approved these changes

2020-10-16 09:46 UTC, merged