Add mission, vision and scope to OpenZaak
open-zaak/open-zaak pull request #749
Opened 2020-10-22 12:14 UTC by Hugo-ter-Doest

Fixes #

**Changes**

[Describe the changes here]

2020-11-27 09:21 UTC, sergei-maertens commented
@Hugo-ter-Doest do you have a status update for this PR? How is it progressing?

2020-12-16 14:15 UTC, joeribekker approved these changes
Sounds good

2020-12-18 13:18 UTC, EdwinCoster commented on OpenZaak_Mission_Vision_Scope.md
> +We believe that Zaakgericht Werken is a best practice for handling requests from citizens and companies. As such ZGW is a way of working that helps to efficiently organise the backoffice of municipal
Zaakgericht Werken = ZGW

2020-12-18 13:19 UTC, EdwinCoster commented on OpenZaak_Mission_Vision_Scope.md
> +We believe that Zaakgericht Werken is a best practice for handling requests from citizens and companies. As such ZGW is a way of working that helps to efficiently organise the backoffice of municipal
Als je 'on the one hand' gebruikt, moet je dan ook 'on the other hand' gebruiken?

2020-12-18 13:22 UTC, EdwinCoster commented on OpenZaak_Mission_Vision_Scope.md
> +We believe that Zaakgericht Werken helps Dutch municipalities to efficiently organise their work and to record and archive their data in a standardised way. The latter is the main concern of OpenZaak
Verander '. This is out of scope' in ', which is out of scope'

2020-12-18 13:24 UTC, EdwinCoster commented on OpenZaak_Mission_Vision_Scope.md
> +OpenZaak complies to the "API's for Zaakgericht Werken". Features or changes that require changes to the standard are not added to OpenZaak before the standard is updated. The OpenZaak partners activ
Verander 'OpenZaak complies to the "API's for Zaakgericht Werken". Features' in 'As OpenZaak complies to the "API's for Zaakgericht Werken", features'.

2020-12-18 13:25 UTC, EdwinCoster requested changes
Ik heb een paar kleine tekstuele aanpassingen voorgesteld.

2021-07-16 22:12 UTC, sergei-maertens commented
I'm closing this PR because no activity has happened in the past half-year.

2021-07-16 22:12 UTC, closed without merging