[WIP] Cannot create documents with same identificatie and bronorganisatie
open-zaak/open-zaak pull request #788
Opened 2020-12-10 11:26 UTC by SilviaAmAm

Fixes #768 

**Changes**

Previously, documents with the same `identificatie` and `bronorganisatie` could be created through the API. There was no unique-together constraint in the database or validator in the document serializer.

A unique-together constraint only on `identificatie` and `bronorganisatie` cannot be added at the database level, because there *can* be multiple documents with same `identificatie` and `bronorganisatie` but different `versie`.

So, for now I only added a `UniekeIdentificatieValidator` [validator](https://github.com/VNG-Realisatie/vng-api-common/blob/master/vng_api_common/validators.py#L301) which checks for the uniqueness of the identificatie within an organisation. I added this validator *only* to the `EnkelvoudigInformatieObjectSerializer` and not to the `EnkelvoudigInformatieObjectWithLockSerializer`. This is because the PATCH request to update a document raises a validation error for when a document is updated (since the `identificatie`/`bronorganisatie` are not unique..).

2020-12-10 15:22 UTC, sergei-maertens requested changes
Small remarks!

2020-12-10 15:22 UTC, sergei-maertens commented on src/openzaak/components/documenten/management/commands/detect_duplicate_eio.py
> +        msg = _(f"Found {len(duplicates)} duplicate records.")
See the earlier interpolation remark.

2020-12-10 15:32 UTC, SilviaAmAm commented on src/openzaak/components/documenten/api/serializers.py
> +    )
I don't think it is anymore, I'm removing it.

2020-12-10 15:42 UTC, sergei-maertens approved these changes

2020-12-16 09:16 UTC, sergei-maertens approved these changes

2020-12-16 09:16 UTC, merged