[WIP] Change CharFilter to a ChoiceFilter
open-zaak/open-zaak pull request #878
Opened 2021-03-03 08:03 UTC by shea-maykinmedia

Fixes #870 

**Changes**

By changing the CharFilter to a ChoiceFilter the user will receive a 400 error response and the following data back rather than a 500 error

```
{
    "type": "http://localhost:8000/ref/fouten/ValidationError/",
    "code": "invalid",
    "title": "Invalid input.",
    "status": 400,
    "detail": "",
    "instance": "urn:uuid:48c051dc-0064-4529-b899-e3b0bd83367b",
    "invalidParams": [
        {
            "name": "status",
            "code": "invalid_choice",
            "reason": "Selecteer een geldige keuze. %(value)s is geen beschikbare keuze."
        }
    ]
}
```

The only thing I don't like is that `%(value)s` is returned instead of the value they passed in but there doesn't seem to be a good solution to fix this.  This happens because `django-filter`  here https://github.com/carltongibson/django-filter/blob/2.0.0/django_filters/utils.py#L320 they use `e.message` without passing in  the proper `params`.  This is fixed in 2.4.0 https://github.com/carltongibson/django-filter/blob/2.4.0/django_filters/utils.py#L315 so we could upgrade to this version but I wasn't sure if that should be done as part of this pull request.  If we do want to do this as part of this PR let me know.

2021-03-08 11:41 UTC, sergei-maertens requested changes
You can do the django-filter update in this PR!

2021-03-08 11:41 UTC, sergei-maertens commented on src/openzaak/components/catalogi/api/filters.py
> +
Please use `DjangoChoices` for this

2021-03-12 09:01 UTC, shea-maykinmedia commented
Updated the django-filters library and I can confirm that the bad query param passed in is also returned in the response.

Eg.

```
{
    "type": "http://localhost:8000/ref/fouten/ValidationError/",
    "code": "invalid",
    "title": "Invalid input.",
    "status": 400,
    "detail": "",
    "instance": "urn:uuid:9a8a92ce-49f7-4cf3-b53a-1a58344f0235",
    "invalidParams": [
        {
            "name": "status",
            "code": "invalid_choice",
            "reason": "Selecteer een geldige keuze. alle is geen beschikbare keuze."
        }
    ]
}
```

2021-03-15 13:49 UTC, sergei-maertens requested changes
Can you fix the requirements here too?

2021-03-15 13:57 UTC, shea-maykinmedia commented
Fixed now! :)

2021-03-18 15:03 UTC, sergei-maertens approved these changes

2021-03-18 15:03 UTC, merged