Feature/910 related zaaktype select
open-zaak/open-zaak pull request #948
Opened 2021-04-12 13:55 UTC by stevenbal

Fixes #910 

**Changes**

* Split the `ZaakTypenRelatie.gerelateerd_zaaktype` field into two: a selection from local Zaaktypen (like a regular foreign key) and a field in which a raw URL can be entered. After saving the form, the value is always saved as a URL, it's just a visual change in the admin

2021-04-12 14:03 UTC, stevenbal commented
![image](https://user-images.githubusercontent.com/29249171/114407402-a3cf1280-9ba8-11eb-9097-4ff1e16cbca8.png)

2021-04-15 09:40 UTC, sergei-maertens requested changes
That's neat!

Very small template code remark, but otherwise good to go.

2021-04-15 09:40 UTC, sergei-maertens commented on src/openzaak/templates/widgets/multiwidget.html
> +    {% if forloop.counter != widget.subwidgets|length %}
could use `forloop.last` instead?

2021-04-29 15:30 UTC, sergei-maertens approved these changes

2021-04-29 15:30 UTC, merged