Log CMIS calls to file
open-zaak/open-zaak pull request #957
Opened 2021-04-21 08:38 UTC by SilviaAmAm

**Changes**
Before the CMIS logs were only shown in the console, now they are logged to a file `cmis.log` by default.

2021-04-28 15:49 UTC, sergei-maertens commented
In deployed environments, this implies that people need to mount a volume on `/app/log` to have persistent logs. This may cause problems with multiple replicas as well.

2021-04-28 15:51 UTC, sergei-maertens requested changes
I would like to see an envvar option to opt in to logging to file rather than stdout, as it's bad practice to write to files in docker containers that are not in a volume. Now the default behaviour is that we get writes to file, which goes against best-practices-by-default.

2021-04-29 16:14 UTC, joeribekker commented
I added this to the discussion for the technical steering group agenda.

2021-07-16 21:52 UTC, sergei-maertens commented
During the technical steering group call it became clear that different logging solutions exist (Loki, Prometheus, Docker Swarm...). Open Zaak should continue to log to stdout, and your logging solution is responsible for the aggregation and filtering options. Since we emit which modules generate the logs, this should be sufficient to filter logs to get the relevant output.

Setting up file-based logging in container contexts is a non-trivial challenge that mostly brings maintenance overhead for the Open Zaak team. Everyone ultimately benefits from using a mature logging solution.

With these arguments, I'm closing this PR without merging it.

2021-07-16 21:52 UTC, closed without merging