✨ Override GeldigheidMixin to handle overlapping dates.
open-zaak/open-zaak pull request #995
Opened 2021-06-28 09:02 UTC by dariomory

Fixes #994

Duplicating the get_overlapping_x.. function is not in line with DRY principles and ideally it should be transferable to all models.

Proposed solutions:
- A. Override GeldigheidMixin.
- B. Create a new mixing to handle the overlapping dates.

**Changes**
Going with solution A, the GeldigheidMixin has been updated to handle overlapping dates for any models using it.

2021-06-28 13:54 UTC, sergei-maertens requested changes
I believe the duplication/function approach exists because these functions are also called in the API endpoints.

We care more about the admin and API endpoint having the same behaviour than sticking to  DRY behaviour.

Is there a way we can achieve both?

2021-06-28 14:01 UTC, sergei-maertens requested changes

2021-06-29 13:38 UTC, dariomory commented
> I believe the duplication/function approach exists because these functions are also called in the API endpoints.
> 
> We care more about the admin and API endpoint having the same behaviour than sticking to DRY behaviour.
> 
> Is there a way we can achieve both?

We can achieve both, at least within DRF's boundaries.

> `verbose_name` is something that is translatable, so this is not a robust check. This logic is also rather "guessing" the field, and that's not something we do in python.
> 
> Please make the field name expliciet by using a class attribute instead, with a sane default on the mixin.

Agree. This was only need due to inconsistent naming of some models fields. What's your opinion on renaming the model field name? That will facilitate the implementation of a DRY function, usable in a single mixin and single validator.

2021-06-29 13:40 UTC, dariomory commented on src/openzaak/components/catalogi/models/mixins.py
> +        omschrijving_field_name = [i for i in self._meta.fields if i.verbose_name == "omschrijving"][0].name
Discussed in https://github.com/open-zaak/open-zaak/pull/995#issuecomment-870608142

2021-07-16 16:42 UTC, sergei-maertens commented
@dariomory sorry to get back so late to this

> We can achieve both, at least within DRF's boundaries.

Please do!

> Agree. This was only need due to inconsistent naming of some models fields. What's your opinion on renaming the model field name? That will facilitate the implementation of a DRY function, usable in a single mixin and single validator.

No, do not rename the model fields. That would require us to apply the mapping in the serializers and potentially update this in a lot of places, for something that is very easily solved with a class attribute.

Additionally, I see code style changes where my code suggestion/required changes are being ignored and the conversation is resolved. That's not okay - use the correct black formatting. Black is included in the dev requirements, so you should be using the black version from your virtualenv.

2021-08-04 10:55 UTC, sergei-maertens approved these changes
Elegant!

2021-08-04 10:55 UTC, merged